package com.alexbros.opidlubnyi.allfootball.helpers;

import android.content.Context;

import com.alexbros.opidlubnyi.allfootball.R;

public class CountryNameHelper {
    public static String get(String c, Context context) {
        switch (c) {
            case "Africa": return context.getString(R.string.string_country_africa);
            case "Albania": return context.getString(R.string.string_country_albania);
            case "Algeria": return context.getString(R.string.string_country_algeria);
            case "Argentina": return context.getString(R.string.string_country_argentina);
            case "Armenia": return context.getString(R.string.string_country_armenia);
            case "Asia": return context.getString(R.string.string_country_asia);
            case "Australia": return context.getString(R.string.string_country_australia);
            case "Australia & Oceania": return context.getString(R.string.string_country_australia_and_oceania);
            case "Austria": return context.getString(R.string.string_country_austria);
            case "Azerbaijan": return context.getString(R.string.string_country_azerbaijan);
            case "Bahrain": return context.getString(R.string.string_country_bahrain);
            case "Belarus": return context.getString(R.string.string_country_belarus);
            case "Belgium": return context.getString(R.string.string_country_belgium);
            case "Bolivia": return context.getString(R.string.string_country_bolivia);
            case "Bosnia and Herzegovina": return context.getString(R.string.string_country_bosnia_and_herzegovina);
            case "Botswana": return context.getString(R.string.string_country_botswana);
            case "Brazil": return context.getString(R.string.string_country_brazil);
            case "Bulgaria": return context.getString(R.string.string_country_bulgaria);
            case "Burkina Faso": return context.getString(R.string.string_country_burkina_faso);
            case "Cameroon": return context.getString(R.string.string_country_cameroon);
            case "Canada": return context.getString(R.string.string_country_canada);
            case "Cape Verde": return context.getString(R.string.string_country_cape_verde);
            case "Chile": return context.getString(R.string.string_country_chile);
            case "China": return context.getString(R.string.string_country_china);
            case "Colombia": return context.getString(R.string.string_country_colombia);
            case "Croatia": return context.getString(R.string.string_country_croatia);
            case "Cyprus": return context.getString(R.string.string_country_cyprus);
            case "Czech Republic": return context.getString(R.string.string_country_czech_republic);
            case "Denmark": return context.getString(R.string.string_country_denmark);
            case "Dominican Republic": return context.getString(R.string.string_country_dominican_republic);
            case "DR Congo": return context.getString(R.string.string_country_dr_congo);
            case "Egypt": return context.getString(R.string.string_country_egypt);
            case "England": return context.getString(R.string.string_country_england);
            case "Estonia": return context.getString(R.string.string_country_estonia);
            case "Ethiopia": return context.getString(R.string.string_country_ethiopia);
            case "Europe": return context.getString(R.string.string_country_europe);
            case "Faroe Islands": return context.getString(R.string.string_country_faroe_islands);
            case "Finland": return context.getString(R.string.string_country_finland);
            case "France": return context.getString(R.string.string_country_france);
            case "FYR Macedonia": return context.getString(R.string.string_country_fyr_macedonia);
            case "Gabon": return context.getString(R.string.string_country_gabon);
            case "Georgia": return context.getString(R.string.string_country_georgia);
            case "Germany": return context.getString(R.string.string_country_germany);
            case "Greece": return context.getString(R.string.string_country_greece);
            case "Hungary": return context.getString(R.string.string_country_hungary);
            case "Iceland": return context.getString(R.string.string_country_iceland);
            case "India": return context.getString(R.string.string_country_india);
            case "Indonesia": return context.getString(R.string.string_country_indonesia);
            case "Ireland": return context.getString(R.string.string_country_ireland);
            case "Israel": return context.getString(R.string.string_country_israel);
            case "Italy": return context.getString(R.string.string_country_italy);
            case "Ivory Coast": return context.getString(R.string.string_country_ivory_coast);
            case "Jamaica": return context.getString(R.string.string_country_jamaica);
            case "Japan": return context.getString(R.string.string_country_japan);
            case "Jordan": return context.getString(R.string.string_country_jordan);
            case "Kazakhstan": return context.getString(R.string.string_country_kazakhstan);
            case "Kenya": return context.getString(R.string.string_country_kenya);
            case "Kyrgyzstan": return context.getString(R.string.string_country_kyrgyzstan);
            case "Latvia": return context.getString(R.string.string_country_latvia);
            case "Lebanon": return context.getString(R.string.string_country_lebanon);
            case "Libya": return context.getString(R.string.string_country_libya);
            case "Lithuania": return context.getString(R.string.string_country_lithuania);
            case "Luxembourg": return context.getString(R.string.string_country_luxembourg);
            case "Malaysia": return context.getString(R.string.string_country_malaysia);
            case "Maldives": return context.getString(R.string.string_country_maldives);
            case "Mauritius": return context.getString(R.string.string_country_mauritius);
            case "Mexico": return context.getString(R.string.string_country_mexico);
            case "Moldova": return context.getString(R.string.string_country_moldova);
            case "Morocco": return context.getString(R.string.string_country_morocco);
            case "Mozambique": return context.getString(R.string.string_country_mozambique);
            case "Namibia": return context.getString(R.string.string_country_namibia);
            case "Netherlands": return context.getString(R.string.string_country_netherlands);
            case "New Zealand": return context.getString(R.string.string_country_new_zealand);
            case "Nicaragua": return context.getString(R.string.string_country_nicaragua);
            case "North & Central America": return context.getString(R.string.string_country_north_and_central_america);
            case "Northern Ireland": return context.getString(R.string.string_country_northern_ireland);
            case "Norway": return context.getString(R.string.string_country_norway);
            case "Palestine": return context.getString(R.string.string_country_palestine);
            case "Philippines": return context.getString(R.string.string_country_philippines);
            case "Poland": return context.getString(R.string.string_country_poland);
            case "Portugal": return context.getString(R.string.string_country_portugal);
            case "Qatar": return context.getString(R.string.string_country_qatar);
            case "Republic Of The Congo": return context.getString(R.string.string_country_republic_of_the_congo);
            case "Romania": return context.getString(R.string.string_country_romania);
            case "Russia": return context.getString(R.string.string_country_russia);
            case "Rwanda": return context.getString(R.string.string_country_rwanda);
            case "Saudi Arabia": return context.getString(R.string.string_country_saudi_arabia);
            case "Scotland": return context.getString(R.string.string_country_scotland);
            case "Serbia": return context.getString(R.string.string_country_serbia);
            case "Singapore": return context.getString(R.string.string_country_singapore);
            case "Slovakia": return context.getString(R.string.string_country_slovakia);
            case "Slovenia": return context.getString(R.string.string_country_slovenia);
            case "Somalia": return context.getString(R.string.string_country_somalia);
            case "South Africa": return context.getString(R.string.string_country_south_africa);
            case "South America": return context.getString(R.string.string_country_south_america);
            case "South Korea": return context.getString(R.string.string_country_south_korea);
            case "Spain": return context.getString(R.string.string_country_spain);
            case "Sweden": return context.getString(R.string.string_country_sweden);
            case "Switzerland": return context.getString(R.string.string_country_switzerland);
            case "Syria": return context.getString(R.string.string_country_syria);
            case "Thailand": return context.getString(R.string.string_country_thailand);
            case "Trinidad and Tobago": return context.getString(R.string.string_country_trinidad_and_tobago);
            case "Tunisia": return context.getString(R.string.string_country_tunisia);
            case "Turkey": return context.getString(R.string.string_country_turkey);
            case "Ukraine": return context.getString(R.string.string_country_ukraine);
            case "United Arab Emirates": return context.getString(R.string.string_country_united_arab_emirates);
            case "USA": return context.getString(R.string.string_country_usa);
            case "Uzbekistan": return context.getString(R.string.string_country_uzbekistan);
            case "Wales": return context.getString(R.string.string_country_wales);
            case "World": return context.getString(R.string.string_country_world);
            default: return c;
        }
    }

}
